### ISSUE TITLE
Connection closed when sending more than 126 bytes in a given message via WebSocket

### ISSUE THREAD

**Issue by KieranDevvs** [davidfowl/BedrockFramework#138]
When sending a message of 126 bytes or more to `System.Net.WebSockets.ClientWebSocket`, the connection forcibly closes.
Any messages with 125 bytes or less are received as expected.

I have only tested `System.Net.WebSockets.ClientWebSocket` under a Blazor WASM client environment thus the issue could be browser API related.

```
Unhandled exception rendering component: The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseSent'
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseSent'
   at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at ClientConnection.ListenAsync(CancellationToken cancellationToken) in BedrockWebSocketTest.Client\ClientConnection.cs:line 28
   at BedrockWebSocketTest.Client.Pages.Index.Start() in BedrockWebSocketTest.Client\Pages\Index.razor:line 16
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Here is a project solution to reproduce the issue: https://github.com/KieranDevvs/BedrockWebSocketTest

Run both projects, and hit start within the index page of the Blazor WASM web app. You should see the connection drop.
Now go into `SessionHandler.cs` within the server project and change `Enumerable.Range(0, 15).Select(x => "really")`
to `Enumerable.Range(0, 14).Select(x => "really")` to lower the message size from 128 to 121. When you run the test this time, the message is received within the client and is printed to the console.

**Comment by KieranDevvs** [comment]
Closed as I have confirmed this it not a Bedrock related issue. Other client implementations such as `WebSocket4Net` seem to be able to read the message fine. I will open this issue on the runtime repo.

**Comment by KieranDevvs** [comment]
I have confirmed this may not be a Bedrock related issue. Other client implementations such as WebSocket4Net seem to be able to read the message fine.

**Comment by KieranDevvs** [comment]
Other client implementations such as `WebSocket4Net` seem to be able to read the message fine. Still trying to figure out if the frame size is being set wrong on the server, or if `System.Net.WebSockets.ClientWebSocket` is reading it wrong: https://www.rfc-editor.org/rfc/rfc6455#section-5.2

**Comment by KieranDevvs** [comment]
Had some time tonight to dig a little deeper, it appears the client is failing when its attempting to validate the payload is `UFT8`.
![image](https://user-images.githubusercontent.com/21192520/153683019-1d1d1b49-9b04-4090-aabe-8ed26b3620bf.png)

It looks like the payload does have some non UTF8 header of some kind:
![image](https://user-images.githubusercontent.com/21192520/153683079-070a44ae-0738-4540-8bb8-5ef8ae817253.png)

**Comment by KieranDevvs** [comment]
Had some time tonight to dig a little deeper, it appears the client is failing when its attempting to validate the header payload is `UFT8`.
![image](https://user-images.githubusercontent.com/21192520/153683019-1d1d1b49-9b04-4090-aabe-8ed26b3620bf.png)

![image](https://user-images.githubusercontent.com/21192520/153684959-403b6902-736b-4d2a-aa8f-15e71a5514eb.png)

![image](https://user-images.githubusercontent.com/21192520/153684964-f76e94b1-7f03-43ae-b8bf-fa27acd2bd9e.png)

**Comment by KieranDevvs** [comment]
Had some time tonight to dig a little deeper, it appears the client is failing when its attempting to validate the header payload is `UFT8`.
![image](https://user-images.githubusercontent.com/21192520/153683019-1d1d1b49-9b04-4090-aabe-8ed26b3620bf.png)

![image](https://user-images.githubusercontent.com/21192520/153684959-403b6902-736b-4d2a-aa8f-15e71a5514eb.png)

![image](https://user-images.githubusercontent.com/21192520/153684964-f76e94b1-7f03-43ae-b8bf-fa27acd2bd9e.png)

**Comment by KieranDevvs** [comment]
Tested the same client out with the following server with success:
```cs
public class ConsoleServer
    {
        static HttpListener httpListener = new HttpListener();
        private static Mutex signal = new Mutex();
        public static async Task Main(string[] args)
        {
            httpListener.Prefixes.Add("http://localhost:8080/");
            httpListener.Start();
            Console.WriteLine("Accepting connections");
            while (signal.WaitOne())
            {
                ReceiveConnection();
            }

        }

        public static async Task ReceiveConnection()
        {
            HttpListenerContext context = await
            httpListener.GetContextAsync();
            if (context.Request.IsWebSocketRequest)
            {
                HttpListenerWebSocketContext webSocketContext = await context.AcceptWebSocketAsync(null);
                WebSocket webSocket = webSocketContext.WebSocket;
                if (webSocket.State == WebSocketState.Open)
                {
                    var payload = Encoding.UTF8.GetBytes($"This is a {string.Join(" ", Enumerable.Range(0, 20).Select(x => "really"))} long message.");
                    await webSocket.SendAsync(payload, WebSocketMessageType.Binary, true, CancellationToken.None);
                }
            }
            signal.ReleaseMutex();
        }
    }
```

**Comment by davidfowl** [comment]
Thanks for the repro
