### ISSUE TITLE
gracefull close client connection

### ISSUE THREAD

**Issue by JanEggers** [davidfowl/BedrockFramework#8]
when I DisposeAsync the client connection I see this in the logs:

Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Bedrock.Framework.SocketConnection.DoSend() in C:\Users\Jan\Source\Repos\MQTTnet\BedrockTransports\Bedrock.Framework\Transports\Sockets\SocketConnection.cs:line 215
   at Bedrock.Framework.SocketConnection.ExecuteAsync() in C:\Users\Jan\Source\Repos\MQTTnet\BedrockTransports\Bedrock.Framework\Transports\Sockets\SocketConnection.cs:line 91

Am I supposed to calling something else before disposeasync or is this a bug?

**Comment by davidfowl** [comment]
When do you call it?

**Comment by JanEggers** [comment]
at the end of my benchmark

https://github.com/JanEggers/MQTTnet/blob/aspnetcore3/Tests/MQTTnet.Benchmarks/MessageProcessingMqttConnectionContextBenchmark.cs

**Comment by davidfowl** [comment]
Need to look into this. It shouldn't happen.

**Comment by davidfowl** [comment]
Dupe of https://github.com/davidfowl/BedrockFramework/issues/19
